version: "3.7"
services:
  consul:
    image: consul:latest
    container_name: consul
    hostname: consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"

  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_USER=guest
     - MYSQL_PASSWORD=guest
     - MYSQL_DATABASE=test
     - TZ=Brazil/East
    volumes:
     - .docker/mysql/data:/var/lib/mysql
  pg:
    image: postgres:9.5
    container_name: pg
    hostname: pg
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB:       test
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data

  # ambassador:
  #   container_name: ambassador
  #   hostname: ambassador
  #   image: quay.io/datawire/ambassador:0.85.0
  #   ports:
  #   - 8080:8080
  #   volumes:
  #     # mount a volume where we can inject configuration files
  #     - ./gateway/config:/ambassador/ambassador-config
  #   environment:
  #   # don't try to watch Kubernetes for configuration changes
  #     AMBASSADOR_NO_KUBEWATCH: no_kubewatch
  #   depends_on:
  #     - consul

  clientsb:
    image: github.com/hfantin/clientsb:latest
    container_name: clientsb
    hostname: clientsb
    ports:
      - 5000:5000
    environment:
      server_port: 5000
      logging_level_root: INFO
      spring_cloud_consul_host: consul
      spring_cloud_consul_port: 8500
      spring_datasource_url: jdbc:mysql://mysql:3306/test
      spring_datasource_username: guest
      spring_datasource_password: guest
    depends_on:
      - mysql
      - consul

  clientgo:
    image: github.com/hfantin/clientgo:latest
    container_name: clientgo
    hostname: clientgo
    ports:
      - 5001:5001
    environment:
      SERVER_PORT: 5001
      DB_HOST: mysql:3306
      DB_USER: guest
      DB_PASS: guest
      DB_NAME: test
      CONSUL_HTTP_ADDR: consul:8500
    depends_on:
     - mysql
     - consul
    links:
      - mysql
  
  clientgo-echo:
    image: github.com/hfantin/clientgo-echo:latest
    container_name: clientgo-echo
    hostname: clientgo-echo
    ports:
      - 5002:5002
    environment:
      SERVER_PORT: 5002
      DB_HOST: mysql:3306
      DB_USER: guest
      DB_PASS: guest
      DB_NAME: test
      CONSUL_HTTP_ADDR: consul:8500
      LOGGER_LEVEL: info
    depends_on:
     - mysql
     - consul
    links:
      - mysql

  clientjs:
    image: github.com/hfantin/clientjs:latest
    container_name: clientjs
    hostname: clientjs
    ports:
      - 5003:5003
    environment:
      SERVER_PORT: 5003
      DB_HOST: mysql
      DB_USER: guest
      DB_PASS: guest
      DB_NAME: test
    depends_on:
     - mysql
    links:
      - mysql
      
  clientrs:
    image: github.com/hfantin/clientrs:latest
    container_name: clientrs
    hostname: clientrs
    ports:
      - 5004:5004
    environment:
      DATABASE_URL: postgres://guest:guest@pg/test
      ROCKET_ADDRESS: 0.0.0.0
      ROCKET_PORT: 5004
    depends_on:
      - pg
    links:
      - pg

  clientex: 
    image: github.com/hfantin/clientex:latest
    container_name: clientex
    hostname: clientex
    ports:
      - 5005:5005
    environment:
      PORT: 5005
      MIX_ENV: prod
      DATABASE_URL: ecto://guest:guest@mysql/test
      POOL_SIZE: 50
      SECRET_KEY_BASE: cerveja
    depends_on:
      - mysql
    links:
      - mysql

  services-consumer:
    image: github.com/hfantin/services-consumer:latest
    container_name: services-consumer
    hostname: services-consumer
    ports:
      - 5006:5006
    environment:
      server_port: 5006
      logging_level_root: INFO
      spring_cloud_consul_host: consul
      spring_cloud_consul_port: 8500
    depends_on:
      - consul