version: "3.7"
services:
  mysql:
    image: mysql:5.7
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_USER=guest
     - MYSQL_PASSWORD=guest
     - MYSQL_DATABASE=test
     - TZ=Brazil/East
    volumes:
     - .docker/mysql/data:/var/lib/mysql
  pg:
    image: postgres:9.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB:       test
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data
  eurekaserver:
    image: com.github.hfantin/eurekasrv:latest
    ports:
      - 8761:8761
    depends_on:
      - mysql
  zuulserver:
    image: com.github.hfantin/zuulsrv:latest
    ports:
      - 5555:5555
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
    depends_on:
      - mysql