version: "3.7"
services:
  mysql:
    image: mysql:5.7
    container_name: "mysql"
    hostname: "mysql"
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_USER=guest
     - MYSQL_PASSWORD=guest
     - MYSQL_DATABASE=test
     - TZ=Brazil/East
    volumes:
     - .docker/mysql/data:/var/lib/mysql
  pg:
    image: postgres:9.5
    container_name: "pg"
    hostname: "pg"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB:       test
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data
  consul:
    image: consul:latest
    container_name: "consul"
    hostname: "consul"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
  eurekaserver:
    image: com.github.hfantin/eurekasrv:latest
    container_name: "eurekaserver"
    hostname: "eurekaserver"
    ports:
      - 8761:8761
    depends_on:
      - mysql
  zuulserver:
    image: com.github.hfantin/zuulsrv:latest
    container_name: "zuulserver"
    hostname: "zuulserver"
    ports:
      - 5555:5555
    environment:  
      server_port: 5555
      logging_level_root: INFO
      eureka_client_serviceUrl_defaultZone: http://eurekaserver:8761/eureka/
    depends_on:
      - eurekaserver
  clientsb:
    image: com.github.hfantin/clientsb:latest
    container_name: "clientsb"
    hostname: "clientsb"
    ports:
      - 5000:5000
    environment:
      server_port: 5000
      logging_level_root: INFO
      spring_cloud_consul_host: consul
      spring_cloud_consul_port: 8500
      spring_datasource_url: jdbc:mysql://mysql:3306/test
      spring_datasource_username: guest
      spring_datasource_password: guest
    depends_on:
      - mysql
      - consul
  clientsb2:
    image: com.github.hfantin/clientsb:latest
    container_name: "clientsb2"
    hostname: "clientsb"
    ports:
      - 5001:5001
    environment:
      server_port: 5001
      logging_level_root: INFO
      spring_cloud_consul_host: consul
      spring_cloud_consul_port: 8500
      spring_datasource_url: jdbc:mysql://mysql:3306/test
      spring_datasource_username: guest
      spring_datasource_password: guest
    depends_on:
      - mysql
      - consul
  clientgo:
    image: clientgov4:latest
    container_name: "clientgo"
    hostname: "clientgo"
    ports:
      - 5002:5002
    environment:
      SERVER_PORT: 5002
      DB_HOST: mysql:3306
      DB_USER: guest
      DB_PASS: guest
      DB_NAME: test
    links:
      - mysql
    # depends_on:
    #   - mysql
    #   - consul
